[project]
name = "py-qimen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cnlunar>=0.2.0",
    "fastapi>=0.115.13",
    "lunar-python>=1.4.4",
    "uvicorn>=0.34.3",
]
